Numpy

é uma biblioteca que fornece um objeto de matriz bidimencional

o numpy oferece uma enorme variedade de maneiras rápidas e eficientes de criar martizes e manipular dados numéricos dentro elas;

as matrizes numpy são mais rápidas e compactas do que as listas python...



In [ ]:
import numpy as np

In [ ]:
# chamando a função array dentro de uma matriz unidimencional 
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [ ]:
# chamando a função array dentro de uma matriz bidimencional
a = np.array([[1, 2, 3],[2, 5, 7]])
print(a)

[[1 2 3]
 [2 5 7]]


In [ ]:
vetor = np.zeros(2)
matriz = np.zeros((2,3))
print(vetor) 
print('------------')
matriz

[0. 0.]
------------


array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
vetor = np.ones(2, dtype=np.int64)
matriz = np.ones((5, 5), dtype=np.float32)
print(vetor)
print(matriz)

In [ ]:
# para usar o empty, basta passar o vetor ou matriz entre os parênteses, assim ele irá criar uma matriz proxima de zero
vetor = np.empty(2)
matriz = np.empty((2,5))
print(vetor)
print(matriz)

[0. 0.]
[[3.24664844e-316 0.00000000e+000 0.00000000e+000 0.00000000e+000
  6.92004047e-310]
 [1.92015271e-052 4.90482874e-062 5.00518543e-090 3.21928782e-057
  6.92008458e-310]]


In [ ]:
# para usar o arrange, basta o valor de até quando criar os itens 
vetor = np.arange(4)
matriz = vetor.reshape(2,2)
print(vetor)
print(matriz)

[0 1 2 3]
[[0 1]
 [2 3]]


In [ ]:
vetor = np.linspace(0, 9, num=4)
print(vetor)
matriz = vetor.reshape(2,2)
print(matriz)

[0. 3. 6. 9.]
[[0. 3.]
 [6. 9.]]


mmq
ajuste de curva 


In [ ]:
import random as rd 


[ 4  6 20 20 12 35 40 27]


2


In [2]:
def soma_valor(a,b):
   print(a + b)

soma_valor(1,2)

3
